# corsican params
# general
PROJECTNAME: 'mfnet'
SESSIONAME: 'mfnet_pidnets'
DEVICE: 'cuda:0'
NUM_WORKERS: 8
ONLINELOG: False
SEED: 200
STOPCOUNTER: 12
VALID_FREQ: 2
WARMUP: 20
# model
MODEL: 'pidnet_s'
NUM_OUTPUTS: 2
PRETRAINED: 'weights/PIDNet_S_ImageNet.pth.tar'
CHECKPOINT: null
# data
TRAINSET: 'lists/train_mfnet.txt'
VALIDSET: 'lists/test_mfnet.txt'
TESTSET: 'lists/test_mfnet.txt'
ROOTDATASET: '../Datasets/'
N_FRAMES: 2
MAX_FR_APART: 0
NUM_CLASSES: 9
CLS_NAMES: ['unlabeled', 'car', 'person', 'bike', 'curve', 'car stop', 'guardrail', 'color cone', 'bump']
#['bg', 'smoke', 'fire']
MODE: 'fusion'
MULTISCALE: True
INTERPOLATION: False
FLIP: True
BRIGHTNESS: False
CONTRAST: False
ONE_INP_AUG: False           # this is for mid fusion, after attention
SINGLE_SOURCE_AUG: False
IGNORE_LABEL: 255
SCALE_FACTOR: 10
CROP_SIZE: [480, 640]
BASE_SIZE: 640
CLASS_WEIGHTS: [1.42312027, 7.5367994, 9.39792775, 9.69024351, 9.90912422, 10.01344351, 10.37182548, 10.27949471, 10.16517178]
ALIGN_CORNERS: True
# loss and optimization
LR: 0.001
BATCHSIZE: 10
EPOCHS: 250
OPTIM: 'ADAM'
SCHED: 'POLY'
USE_OHEM: False
OHEMTHRES: 0.9
OHEMKEEP: 131072
WD: 0.0000012
MOMENTUM: 0.9
NESTEROV: false
BALANCE_WEIGHTS: [0.4, 1.0]
T_THRESH_BDLOSS: 0.8
BD_WEIGHT: 1.0
SB_WEIGHTS: 1.0
