# corsican params
# general
PROJECTNAME: 'Async'
SESSIONAME: 'Trainv3'
DEVICE: 'cpu'
NUM_WORKERS: 10
ONLINELOG: False
SEED: 200
STOPCOUNTER: 12
VALID_FREQ: 2
WARMUP: 5
# model
MODEL: 'pidnet_s'
NUM_OUTPUTS: 2
PRETRAINED: null
CHECKPOINT: null
# data
TRAINSET: 'lists/train_flm.txt'
VALIDSET: 'lists/test_flm.txt'
TESTSET: 'lists/test_flm.txt'
ROOTDATASET: '../Datasets/'
MAX_FR_APART: 6
NUM_CLASSES: 3
CLS_NAMES: ['bg', 'smoke', 'fire']
MODE: 'fusion'
MULTISCALE: True
FLIP: True
BRIGHTNESS: False
CONTRAST: False
ONE_INP_AUG: False           # this is for mid fusion, after attention
SINGLE_SOURCE_AUG: False
IGNORE_LABEL: 255
SCALE_FACTOR: 9
CROP_SIZE: [272, 336]
BASE_SIZE: 336
#0.22256892, 0.30859346, 0.46883762 (flame+finland LW) [bg, smoke, fire]
# 0.11, 0.14, 0.75
CLASS_WEIGHTS: [0.21, 0.34, 0.45]
ALIGN_CORNERS: True
# loss and optimization
LR: 0.0001
BATCHSIZE: 8
EPOCHS: 400
OPTIM: 'ADAM'
USE_OHEM: False
OHEMTHRES: 0.9
OHEMKEEP: 131072
WD: 0.0001
MOMENTUM: 0.9
NESTEROV: false
BALANCE_WEIGHTS: [0.4, 1.0]
T_THRESH_BDLOSS: 0.8
BD_WEIGHT: 1.0
SB_WEIGHTS: 1.0
